
name: test
on: 
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: windows-lastest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          host: localhost
          user: Piriyapong
          key: ${{ secrets.OMG_SECRET}}
          port: 22 
          script: |
            pwd
